from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
driver=webdriver.Chrome(r"C:\Users\CHANDAN SAHU\Desktop\chromedriver")
driver.get("https://bol.navgurukul.org/#/login")
time.sleep(15)
driver.find_element_by_css_selector("#mx_Field_2").send_keys("Chandan19")
time.sleep(2)
driver.find_element_by_xpath('//*[@id="mx_Field_3"]').send_keys("navgurukul")
driver.find_element_by_xpath('//*[@id="matrixchat"]/div/div[1]/div[2]/div[2]/div/form/input').click()
print("its working")
time.sleep(12)
driver.find_element_by_xpath('//*[@id="matrixchat"]/div/div[1]/div[2]/div/div/div/div[2]/div[2]').click()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="matrixchat"]/div/div[1]/div[2]/div/div/div/div/div[1]').click()
time.sleep(5)
driver.find_element_by_xpath('//*[@id="matrixchat"]/div/div[1]/div/div[2]/div/div[2]/div[1]').click()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="matrixchat"]/div/div[1]/div/div[2]/div/div[2]/div[1]').click()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="matrixchat"]/div/div[1]/div/div[2]/div/div[2]/div[1]').click()
time.sleep(5)
print("its working")
driver.find_element_by_xpath('//*[@id="matrixchat"]/div/div[2]/div[1]/aside/div[3]/div[3]/div/div[2]').click()
print("its warking")
time.sleep(5)
driver.find_element_by_xpath('//*[@id="mx_Dialog_StaticContainer"]/div/div[1]/div[3]/div[2]/div[1]/div[1]').click()
print("its working")
time.sleep(8)
# driver.find_element_by_xpath('//*[@id="mx_Dialog_StaticContainer"]/div/div[1]/div[3]/div[2]/div[1]/div[1]').send_keys("biju")
# print("its warkin")
driver.find_element_by_xpath('//*[@id="mx_Dialog_StaticContainer"]/div/div[1]/div[3]/div[2]/div[3]/div[1]/div[1]').click()
print("its working")
driver.find_element_by_xpath('//*[@id="mx_Dialog_StaticContainer"]/div/div[1]/div[3]/div[2]/div[1]/div[2]/div').click()
print("its working")
driver.find_element_by_xpath('//*[@id="matrixchat"]/div/div[2]/main/div[2]/div/div[4]/div/div/div[3]').click()
print('its working')
driver.find_element_by_xpath('//*[@id="matrixchat"]/div/div[2]/main/div[2]/div/div[4]/div/div/div[3]/div[2]/div[2]').send_keys("hello",Keys.ENTER)
print("its working")